name: qleedo
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # amazon_like_filter: ^1.0.0
  amazon_like_filter: 
    path: ./plugins/amazon_like_filter-1.0.0/
  connectivity_plus: ^6.1.1
  http: ^1.2.2
  intl: ^0.19.0
  audioplayers: ^6.1.0
  flutter_tts: ^4.2.1
  localstorage: ^5.0.0
  youtube_player_iframe: ^5.2.1
  lottie: ^3.3.0
  syncfusion_flutter_calendar: ^28.1.37
  rxdart: ^0.28.0
  #firebase_crashlytics: ^4.2.0
  flutter_signin_button: ^2.0.0
  #firebase_auth: ^5.3.4
  #firebase_core: ^3.9.0
  #google_sign_in: ^6.2.2
  #google_sign_in_web: ^0.12.4+3
  #firebase_analytics: ^11.3.6
  #firebase_messaging: ^15.1.6
  universal_html: ^2.2.4
  #google_maps_flutter_web: ^0.5.10
  #google_maps_flutter: ^2.10.0
  shared_preferences: ^2.3.5
  flutter_spinkit: ^5.2.1
  provider: ^6.1.2
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0
  fluttertoast: ^8.2.10
  loading_overlay: ^0.4.2
  scroll_to_index: ^3.0.1
  indexed_list_view: ^4.0.0
  flutter_picker: ^2.1.0
  flutter_inappwebview: ^6.1.5
  custom_pop_up_menu: ^1.2.4
  fl_paging: ^2.2.0
  infinite_scroll_pagination: ^4.1.0
  video_player: ^2.9.2
  auto_size_text: ^3.0.0
  cupertino_setting_control: ^1.1.0
  flutter_search_bar: ^3.0.0
 #   git:
  #    url: https://github.com/renefloor/flutter_search_bar.git
  table_calendar: ^3.1.3
  connectivity_for_web: ^0.4.0+1
  cached_network_image: ^3.4.1
  flutter_animate: ^4.5.2
  flutter_staggered_animations: ^1.1.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/prayer/
    - assets/js/
    - assets/images/banner/
    - assets/images/logotop/
    - assets/images/logowithtitle/
    - assets/images/saints/
    - assets/images/seperator/
    - assets/bible/JsonBibile.json
    - assets/bible/eng/1/
    - assets/bible/eng/2/
    - assets/bible/eng/3/
    - assets/bible/eng/4/
    - assets/bible/eng/5/
    - assets/bible/eng/6/
    - assets/bible/eng/7/
    - assets/bible/eng/8/
    - assets/bible/eng/9/
    - assets/bible/eng/10/
    - assets/bible/eng/11/
    - assets/bible/eng/12/
    - assets/bible/eng/13/
    - assets/bible/eng/14/
    - assets/bible/eng/15/
    - assets/bible/eng/16/
    - assets/bible/eng/17/
    - assets/bible/eng/18/
    - assets/bible/eng/19/
    - assets/bible/eng/20/
    - assets/bible/eng/21/
    - assets/bible/eng/22/
    - assets/bible/eng/23/
    - assets/bible/eng/24/
    - assets/bible/eng/25/
    - assets/bible/eng/26/
    - assets/bible/eng/27/
    - assets/bible/eng/28/
    - assets/bible/eng/29/
    - assets/bible/eng/30/
    - assets/bible/eng/31/
    - assets/bible/eng/32/
    - assets/bible/eng/33/
    - assets/bible/eng/34/
    - assets/bible/eng/35/
    - assets/bible/eng/36/
    - assets/bible/eng/37/
    - assets/bible/eng/38/
    - assets/bible/eng/39/
    - assets/bible/eng/40/
    - assets/bible/eng/41/
    - assets/bible/eng/42/
    - assets/bible/eng/43/
    - assets/bible/eng/44/
    - assets/bible/eng/45/
    - assets/bible/eng/46/
    - assets/bible/eng/47/
    - assets/bible/eng/48/
    - assets/bible/eng/49/
    - assets/bible/eng/50/
    - assets/bible/eng/51/
    - assets/bible/eng/52/
    - assets/bible/eng/53/
    - assets/bible/eng/54/
    - assets/bible/eng/55/
    - assets/bible/eng/56/
    - assets/bible/eng/57/
    - assets/bible/eng/58/
    - assets/bible/eng/59/
    - assets/bible/eng/60/
    - assets/bible/eng/61/
    - assets/bible/eng/62/
    - assets/bible/eng/63/
    - assets/bible/eng/64/
    - assets/bible/eng/65/
    - assets/bible/eng/66/
    - assets/bible/mlm/1/
    - assets/bible/mlm/2/
    - assets/bible/mlm/3/
    - assets/bible/mlm/4/
    - assets/bible/mlm/5/
    - assets/bible/mlm/6/
    - assets/bible/mlm/7/
    - assets/bible/mlm/8/
    - assets/bible/mlm/9/
    - assets/bible/mlm/10/
    - assets/bible/mlm/11/
    - assets/bible/mlm/12/
    - assets/bible/mlm/13/
    - assets/bible/mlm/14/
    - assets/bible/mlm/15/
    - assets/bible/mlm/16/
    - assets/bible/mlm/17/
    - assets/bible/mlm/18/
    - assets/bible/mlm/19/
    - assets/bible/mlm/20/
    - assets/bible/mlm/21/
    - assets/bible/mlm/22/
    - assets/bible/mlm/23/
    - assets/bible/mlm/24/
    - assets/bible/mlm/25/
    - assets/bible/mlm/26/
    - assets/bible/mlm/27/
    - assets/bible/mlm/28/
    - assets/bible/mlm/29/
    - assets/bible/mlm/30/
    - assets/bible/mlm/31/
    - assets/bible/mlm/32/
    - assets/bible/mlm/33/
    - assets/bible/mlm/34/
    - assets/bible/mlm/35/
    - assets/bible/mlm/36/
    - assets/bible/mlm/37/
    - assets/bible/mlm/38/
    - assets/bible/mlm/39/
    - assets/bible/mlm/40/
    - assets/bible/mlm/41/
    - assets/bible/mlm/42/
    - assets/bible/mlm/43/
    - assets/bible/mlm/44/
    - assets/bible/mlm/45/
    - assets/bible/mlm/46/
    - assets/bible/mlm/47/
    - assets/bible/mlm/48/
    - assets/bible/mlm/49/
    - assets/bible/mlm/50/
    - assets/bible/mlm/51/
    - assets/bible/mlm/52/
    - assets/bible/mlm/53/
    - assets/bible/mlm/54/
    - assets/bible/mlm/55/
    - assets/bible/mlm/56/
    - assets/bible/mlm/57/
    - assets/bible/mlm/58/
    - assets/bible/mlm/59/
    - assets/bible/mlm/60/
    - assets/bible/mlm/61/
    - assets/bible/mlm/62/
    - assets/bible/mlm/63/
    - assets/bible/mlm/64/
    - assets/bible/mlm/65/
    - assets/bible/mlm/66/
    - assets/json/

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-light.ttf
        - asset: assets/fonts/Lato-Medium.ttf
        - asset: assets/fonts/Lato-Thin.ttf
          weight: 700
